# Deployment 2: Replica count: 1; containers per pod: 1; req defined only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1-1-req
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-1-1-req
  template:
    metadata:
      labels:
        app: deploy-1-1-req
    spec:
      containers:
      - name: container
        image: docker.io/sandipandevzero/dakr-stress-single:latest
        imagePullPolicy: Always
        env:
        - name: CPU_CORES
          value: "4"
        - name: CPU_LOAD
          value: "30"
        - name: CPU_DURATION
          value: "180"
        - name: RAM_MB
          value: "2500"
        - name: RAM_DURATION
          value: "180"
        - name: SLEEP_MIN
          value: "120"
        - name: SLEEP_MAX
          value: "6000"
        resources:
          requests:
            cpu: 1000m
            memory: 256Mi
